### ISSUE TITLE
Did you use another board?

### ISSUE THREAD

**Issue by jvlobo** [Josecvegara/Lite3DP_Modfirmware#1]
When trying to compile and upload to the Arduino Pro Mini board that comes with the Lite3DP, I get an error because the sketch is too big.

![Screenshot 2022-05-05 at 22 11 06](https://user-images.githubusercontent.com/5671420/167026301-09113a11-ee13-4efb-93a8-dca4a3606337.png)

**Comment by Josecvegara** [comment]
Las librerías están modificadas para hacerlas más pequeñas. Tienes que instalar las librerías modificadas.

**Comment by Josecvegara** [comment]
https://github.com/Josecvegara/Lite3DP_Modfirmware

**Comment by jvlobo** [comment]
Perfecto, gracias :)
